<h2><?php echo $this->title;?></h2>
<div id="container">
  <?php if ( count($this->albums) > 0 ) {?>
  <div id="cpanel">
    <?php foreach($this->albums as $album) : ?>
    <?php 
		$cover = $album['picture'] ? $album['picture'] : 'noimage.png' ;
	?>
    <div class="icon">
    <a href="<?php echo $this->url(array('controller'=>'photo',
'action'=>'index'));?>?id=<?php echo $album['id'];?>"> <img src="<?php echo $this->baseUrl(); ?>/phpthumb/phpThumb.php?src=../images/gallery/<?php echo $cover;?>&w=140&h=110" /> <span><?php echo ucwords($album['name'])?></span></a>
    </div>
    <?php endforeach; ?>
  </div>
  <?php }else{?>
  No Album Found.
  <?php }?>
  <div class="clear"  ></div>
</div>
