<h2><?php echo $this->title;?></h2>
<div class="right-align"><a href="<?php echo $this->url(array('controller'=>'album',
'action'=>'create'));?>">Add new album</a></div>
<div id="container">
  <?php if ( count($this->albums) > 0 ) {?>
  <div id="cpanel">
    <?php foreach($this->albums as $album) : ?>
    <?php 
		$cover = ($album['cover']) ? $album['cover'] : 'noimage.png' ;
	?>
    <div class="icon">
    <a href="<?=$this->baseUrl();?>/photo?album=<?php echo $album['id'];?>"> <img src="phpthumb/phpThumb.php?src=../images/gallery/<?php echo $cover;?>&w=140&h=110" /> <span><?php echo ucwords($album['name'])?></span></a>
    </div>
    <?php endforeach; ?>
  </div>
  <?php }else{?>
  No Album Found.
  <?php }?>
  <div class="clear"  ></div>
</div>
