<script type="text/javascript">

baseURL = '<?php echo $this->baseUrl();?>';
$(document).ready(function(){
	$(".dPhoto").css("display", "none");
	$(".dPhotoDelete").css("display", "none");
});

$(function() {
	$('#cpanel a').lightBox({
	imageLoading: '<?php echo $this->baseUrl();?>/images/lightbox-ico-loading.gif',
	imageBtnClose: '<?php echo $this->baseUrl();?>/images/lightbox-btn-close.gif',
	imageBtnPrev: '<?php echo $this->baseUrl();?>/images/lightbox-btn-prev.gif',
	imageBtnNext: '<?php echo $this->baseUrl();?>/images/lightbox-btn-next.gif',
   });

});

function settitle(thisEle)
{
	$(thisEle).attr('title', '<a href="#">Download</a>');
	$(thisEle).children(".dPhoto").css("display", "none");
	$(thisEle).children(".dPhotoDelete").css("display", "none");
}
function removetitle(thisEle)
{
	$(thisEle).attr('title', '');
	$(thisEle).children(".dPhoto").css("display", "block");
	$(thisEle).children(".dPhotoDelete").css("display", "block");
}

function removeHref(DivEle)
{
	 var parentTag = $(DivEle).parent();
	 $(parentTag).attr("href", "javascript:void(0)")

	$(parentTag).click(function (event) 
	{ 
		 event.preventDefault(); 
		 //here you can also do all sort of things 
	});
}

function setHref(DivEle, hrefValue)
{
	 var parentTag = $(DivEle).parent();
	 $(parentTag).attr("href", hrefValue);

	 $(parentTag).removeAttr('disabled');
}

function deletePic( albumId, picId  )
{
	if(!confirm('Are you sure you want to delete this picture?'));
		return false;
	setTimeout('$( "#jquery-overlay" ).click()', 0);
	 URL = baseURL+'/photo/delete/pic/'+picId+'/album/'+albumId;
	window.location = URL;
}

function Imagedownload (frmId, url)
{
	oIFrm = document.getElementById(frmId);
	oIFrm.src = url;
	setTimeout('$( "#jquery-overlay" ).click()', 0);
}

</script>
<div id="breadcrumbs"><?php echo $this->title;?></div>
<p>&nbsp;</p>
<?php if ( $this->album['author'] == $this->userid ) {?>
<div class="right-align">
<a href="<?php echo $this->baseUrl();?>/photo/create/album/<?php echo $this->album['id'];?>">Upload Photos</a> |

<a href="<?php echo $this->baseUrl();?>/album/update/id/<?php echo $this->album['id'];?>" onclick="alert('This link will direct you to album editor page'); return false;">Edit album</a></div>
<?php } ?>

<?php if ( $this->album['author'] == $this->userid ) {?>
<div class="left-align">
<a href="<?php echo $this->baseUrl();?>/album/delete/album/<?php echo $this->album['id'];?>" onclick="return confirm('Are you sure you want to delete this album?');">Delete Album</a>
</div>
<?php } ?>

<div id="container">
  <?php if ( count($this->albumPhoto) > 0 ) {?>
  <div id="cpanel">
    <?php foreach($this->albumPhoto as $photo) : ?>
    <?php 
		$myURL = $this->url( array('controller'=>'photo','action'=>'download') );
	?>
    <div class="icon">
    <a onmouseout="settitle(this);" onclick="settitle(this);" title="<?php //echo $title;?>" onmouseover="removetitle(this);" href="<?=$this->baseUrl();?>/phpthumb/phpThumb.php?src=../images/gallery/<?php echo $photo['picture'];?>&w=800&h=600"> <img src="<?=$this->baseUrl();?>/phpthumb/phpThumb.php?src=../images/gallery/<?php echo $photo['picture'];?>&w=140&h=110" /> <span><?php echo ucwords($photo['name'])?></span>
    <br />
    <?php if ( $this->album['author'] == $this->userid ) {?>
    <span class="dPhoto" onclick="deletePic('<?php echo $this->album['id'];?>', '<?php echo $photo['id'];?>');" onmouseover="removeHref(this);" onmouseout="setHref(this,'<?=$this->baseUrl();?>/phpthumb/phpThumb.php?src=../images/gallery/<?php echo $photo['picture'];?>&w=800&h=600');">Delete</span>
    <?php }?>
    <span class="dPhotoDelete" onclick="Imagedownload('<?php echo "myIFrm_".$photo['id'];?>', '<?php echo $myURL.'?imagefile='.$photo['picture'];?>');" onmouseover="removeHref(this);" onmouseout="setHref(this,'<?=$this->baseUrl();?>/phpthumb/phpThumb.php?src=../images/gallery/<?php echo $photo['picture'];?>&w=800&h=600');">Download</span>
    <iframe id="myIFrm_<?php echo $photo['id'];?>" src="" style="visibility:hidden;"></iframe>
    <br />
    </a>
    </div>
    <?php endforeach; ?>
  </div>
  <?php }else{?>
  No Photo Found.
  <?php }?>
  <div class="clear"  ></div>
</div>