<?php
// block any attempt to the filesystem
$filePath ='images/gallery/';

if ( isset( $this->imageFile ) && basename( $this->imageFile ) == $this->imageFile ) 
{
	$filename = $this->imageFile;
}
else 
{
	$filename = NULL;
} 

$err = '<p style="color:#990000">Sorry, the file you are requesting is unavailable.</p>'; 

if (!$filename) 
{
	// if variable $filename is NULL or false display the message
	echo $err;
} 
else 
{
	// define the path to your download folder plus assign the file name
	$path = $filePath.$filename;
	// check that file exists and is readable
	if (file_exists($path) && is_readable($path)) 
	{
		// get the file size and send the http headers
		$size = filesize($path);
		$filetype = strtolower(end(explode('.', $filename)));
		switch($filetype) {
		    case 'jpg':
		    case 'jpeg':
		        header('Content-Type: image/jpg');
		        break;
		    case 'png':
		        header('Content-Type: image/png');
		        break;
		    case 'gif':
		        header('Content-Type: image/gif');
		        break;
		    default:
		        die("Content-Type error");
		}
		header('Content-Length: '.$size);
		header('Content-Disposition: attachment; filename='.$filename);
		header('Content-Transfer-Encoding: binary');
		
		// open the file in binary read-only mode
		// display the error messages if the file can´t be opened
		$file = @fopen($path, 'rb');
		
		if ($file) 
		{
			// stream the file and exit the script when complete
			fpassthru($file);
			exit;
		} 
		else 
		{
			echo $err;
		}
	} 
	else 
	{
		echo $err;
	}
}
?>