<script type="text/javascript">
$(function() {
	$('#cpanel a').lightBox({
	imageLoading: '<?php echo $this->baseUrl();?>/images/lightbox-ico-loading.gif',
	imageBtnClose: '<?php echo $this->baseUrl();?>/images/lightbox-btn-close.gif',
	imageBtnPrev: '<?php echo $this->baseUrl();?>/images/lightbox-btn-prev.gif',
	imageBtnNext: '<?php echo $this->baseUrl();?>/images/lightbox-btn-next.gif',
   });

});
</script>
<h2><?php echo $this->title;?></h2>
<div class="left-align">
<!--<a href="<?php //echo $this->url(array('album'=>$this->album['id'],'controller'=>'album','action'=>'update'));?>">Edit Album</a>&nbsp;|-->
<a href="<?php echo $this->url(array('album'=>$this->album['id'],'controller'=>'album','controller'=>'album','action'=>'delete'));?>">Delete Album</a>
</div>
<div class="right-align"><a href="<?php echo $this->url(array('album'=>$this->album['id'],'controller'=>'photo',
'action'=>'create'));?>">Upload Photos</a></div>
<div id="container">
  <?php if ( count($this->albumPhoto) > 0 ) {?>
  <div id="cpanel">
    <?php foreach($this->albumPhoto as $photo) : ?>
    <?php 
		//$cover = ($album['cover']) ? $album['picture'] : 'noimage.png' ;
	?>
    <div class="icon">
    <a href="<?=$this->baseUrl();?>/phpthumb/phpThumb.php?src=../images/gallery/<?php echo $photo['picture'];?>&w=800&h=600"> <img src="<?=$this->baseUrl();?>/phpthumb/phpThumb.php?src=../images/gallery/<?php echo $photo['picture'];?>&w=140&h=110" /> <span><?php echo ucwords($photo['name'])?></span></a>
    </div>
    <?php endforeach; ?>
  </div>
  <?php }else{?>
  No Photo Found.
  <?php }?>
  <div class="clear"  ></div>
</div>
