<?php ini_set('display_errors',1); ?>
<?php echo $this->doctype(); ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>PhotoAlbum </title>
<?php //echo $this->headLink()->appendStylesheet('css/style.css') ?>
<link rel="stylesheet" type="text/css" media="screen" href="<?=$this->baseUrl();?>/css/style.css" />
<link rel="stylesheet" type="text/css" href="<?=$this->baseUrl();?>/css/jquery.lightbox-0.5.css" media="screen" />

<?php echo $this->jQuery(); ?>
<script type="text/javascript" src="<?=$this->baseUrl();?>/js/jquery.lightbox-0.5.pack.js"></script>

</head>
<body>
<?php //echo $this->baseUrl();?>
<div id="outerDIv">
  <div id="img-top"></div>
  <div id="innderDiv">
    <div id="header">
    <div id="homeLink" class="transparent" onClick="window.location='<?=$this->baseUrl();?>';" ></div>
	</div>
    <div id="contents">
      <div id="content-main"><?php echo $this->layout()->content; ?></div>
      <div class="right-col"></div>
      <div id="right-column">
	 
<?php
$auth = Zend_Auth::getInstance();
if ($auth->hasIdentity()):
?>

    <a href="<?php echo $this->baseUrl(); ?>/user/show">My profile</a><br />
    <br />
    
    <a href="<?php echo $this->url(array('controller'=>'album',
    'action'=>'create'));?>">Create album</a><br />
    <br />

    <a href="<?php echo $this->baseUrl(); ?>/user/logout">Log out</a><br />
    <br />

    <?php

else:

	$form = new Zend_Form;
    $form->setAction($this->baseUrl().'/user/login')
		 ->setMethod('post');
    
    $username = $form->createElement('text', 'email');
    $username->addValidator('alnum')
    		 ->addValidator('regex', false, array('/^[a-z]+/'))
    		 ->addValidator('stringLength', false, array(6, 20))
    		 ->setRequired(true)
    		 ->setLabel('Email')
    		 ->addFilter('StringToLower');
    
    $password = $form->createElement('password', 'password');
    $password->addValidator('StringLength', false, array(6))
    		 ->setRequired(true)
    		 ->setLabel('Password');
    
    $form->addElement($username)
    	 ->addElement($password)
    	 ->addElement('submit', 'login', array('label' => 'Login'));
    
	echo $form;

    ?><br />

	<a href="<?php echo $this->baseUrl(); ?>/user/create">Sing up</a><br />
	<br />

<?php endif; ?>

<a href="<?php echo $this->baseUrl(); ?>/user">User list</a>
	  </div>
    </div>
    <div class="clear"></div>
  </div>
  <div id="img-bottom"></div>
</div>
</body>
</html>