<h2><?php echo $this->title;?></h2>
<?php echo $this->user['email']; ?>

<?php if($this->my_profile): ?>
<div class="right-align">
<a href="<?php echo $this->url(array('controller'=>'album',
'action'=>'create'));?>" onclick="alert('This link will direct you to the album creation page in the future'); return false;">Create album</a>
</div>
<?php endif; ?>


<div class="right-align"> <!-- remove add as friend link --></div>
<div id="container">
	
  <?php if ( count($this->albums) > 0 ) {?>
  <div id="cpanel">
    <?php $i = 0; foreach($this->albums as $album) : ?>
    <?php 
		$cover = ($album['picture']) ? $album['picture'] : 'noimage.png' ;
	?>
    <div class="icon">
        <a href="<?php echo $this->url(array('controller'=>'album',
'action'=>'show'));?>?id=<?php echo $album['id']; ?>">
<img src="<?php echo $this->baseUrl(); ?>/phpthumb/phpThumb.php?src=../images/gallery/<?php echo $cover;?>&w=140&h=110" width="140" height="110" />
        <span><?php echo ucwords($album['name'])?></span></a>
    </div>
    <?php endforeach; ?>
  </div>
   
  
  <?php }else{?>
  No Album Found.
  <?php }?>
    
  <div class="clear"  ></div>
</div>
