<h2><?php echo $this->title;?></h2>

<div class="right-align"><?php echo $this->ajaxLink("Add to friends list",
"/user/friend", array('update' => '#left-content')); ?></div>
<div id="container">
	
  <?php if ( count($this->albums) > 0 ) {?>
  <div id="cpanel">
    <?php foreach($this->albums as $album) : ?>
    <div class="icon">
        <a href="#"><img src="../images/gallery/1.jpg" width="140" height="110" />
        <span><?php echo ucwords($albums['title'])?></span></a>
    </div>
    <?php endforeach; ?>
  </div>
   
  
  <?php }else{?>
  No Album Found.
  <?php }?>
    
  <div class="clear"  ></div>
</div>


<h2>Friends list</h2>
